// All user-facing copy for the site, keyed by language ('en' | 'uz').
// Uzbek strings are taken from the v2 reference doc; English is the site's
// existing copy plus the doc's expanded "About" text. Each language renders its
// own arrays, so bullet counts don't need to match between languages.

export const content = {
  en: {
    nav: {
      links: [
        { label: 'Home', href: '#home' },
        { label: 'About', href: '#about' },
        { label: 'Services', href: '#services' },
        { label: 'Why Us', href: '#why-us' },
        { label: 'Contact', href: '#contact' },
      ],
      quote: 'Get Free Quote',
    },
    hero: {
      eyebrow: 'NAATI Certified Translator & Interpreter',
      titleA: 'Uzbek',
      titleB: 'English',
      titleTail: 'Translation & Interpreting',
      body: 'Whether you need a birth certificate translated for a visa application, an interpreter for an appointment, or help communicating across languages, I provide clear, reliable support from start to finish.',
      cta: 'Request a Quote',
      phone: '+61 494 003 881',
      phoneHref: 'tel:+61494003881',
      imgAlt: 'Certified Uzbek–English translator at work',
    },
    about: {
      eyebrow: 'What We Offer',
      heading: 'Comprehensive Language Services',
      body: [
        {
          lead: 'NAATI Certified.',
          text: ' NAATI (National Accreditation Authority for Translators and Interpreters) is Australia’s national certification body for translators and interpreters. Many government departments, migration agents, universities, and other official organisations require or recommend NAATI-certified translations for official documents.',
        },
        {
          text: 'From certified document translation to professional interpreting, I provide reliable language services for individuals, businesses, researchers, and community organisations.',
        },
      ],
    },
    services: {
      eyebrow: 'Our Services',
      heading: 'Translation & Interpreting Services',
      body: 'From certified documents to live interpreting, I provide reliable language support across Uzbek, English, and Russian.',
      cta: 'Request a Quote',
      items: [
        {
          title: 'Certified Document Translations',
          img: '/images/service-certified.png',
          desc: 'Official translations for immigration, education, legal, and other official purposes.',
          bullets: [
            'Birth Certificates',
            'Marriage Certificates',
            'Academic Transcripts & Diplomas',
            'Driver Licences',
            'Passports & Identity Documents',
          ],
        },
        {
          title: 'Regular Translations',
          img: '/images/service-regular.png',
          desc: 'Translations to and from English, Uzbek, and Russian.',
          bullets: ['Plain text', 'Commercial text', 'Educational & academic materials'],
        },
        {
          title: 'Interpreting',
          img: '/images/service-interpreting.png',
          desc: 'Professional interpreting across Uzbek, English, and Russian.',
          bullets: [
            'Over the phone',
            'Zoom, Telegram & Skype calls',
            'On site (Brisbane & Tashkent)',
          ],
        },
        {
          title: 'Editing & Proofreading',
          img: '/images/service-editing.png',
          desc: 'Polishing your text so it reads clearly, accurately, and grammatically.',
          bullets: ['Coursework', 'Research papers', 'Diploma work', 'Homework & written assignments'],
        },
      ],
    },
    whyUs: {
      eyebrow: 'Why Choose Us',
      heading: 'Language expertise backed by professional experience',
      body: 'We specialise in Uzbek, English, and Russian, allowing us to deliver translations that are not only linguistically accurate but also culturally appropriate. Whether you need a certified document translated, an interpreter for an important meeting, or assistance with academic and business communication, we provide reliable, confidential, and personalised service.',
      points: [
        'NAATI Certified in Uzbek and English translations',
        'Translations that meet official institution requirements',
        'Accurate, natural, and culturally appropriate translations',
        'Fast turnaround times',
        'Confidential handling of all documents',
        'Personal service from an experienced language professional',
      ],
      badge: 'NAATI',
      badgeSub: 'Certified professional',
      img1Alt: 'NAATI certification, certificates and dictionary on a desk',
      img2Alt: 'Translator’s desk with laptop showing Uzbek and English',
    },
    cta: {
      eyebrow: 'Ready to Get Started?',
      heading: 'Get Your Free Quote Today',
      body: 'Contact us for a free consultation and quote. We are here to help with all your translation needs.',
      cta: 'Get My Free Quote',
      guarantee: '100% acceptance guaranteed by Australian immigration & institutions.',
      guaranteeAlt: 'Australian Government Department of Immigration — 100% guaranteed acceptance',
    },
    contact: {
      eyebrow: 'Contact Us',
      heading: 'Get a Free Quote',
      body: 'Reach out with your documents or questions and I’ll get back to you with a free, no-obligation quote.',
      cta: 'Upload & Get a Quote',
      emailLabel: 'Email',
      auPhoneLabel: 'Australian Phone',
      uzPhoneLabel: 'Uzbek Phone',
      basedLabel: 'Based In',
      based: 'Brisbane, Australia & Tashkent, Uzbekistan',
    },
    footer: {
      rights: 'All rights reserved.',
    },
    quote: {
      eyebrow: 'Free, No-Obligation Quote',
      heading: 'Get Your Free Quote',
      intro: 'Upload your document(s) and tell us what you need. We’ll review them and email you a quote.',
      documents: 'Your documents',
      dropLead: 'Drag & drop files here, or ',
      browse: 'browse',
      dropHint: 'PDF, Word, or image files — you can add several',
      removeFile: 'Remove',
      name: 'Full name',
      namePlaceholder: 'Jane Doe',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      phone: 'Phone',
      phonePlaceholder: '+61 400 000 000',
      serviceType: 'Service type',
      selectService: 'Select a service',
      serviceTypes: [
        'Certified translation',
        'Regular translation',
        'Interpreting',
        'Editing & proofreading',
      ],
      from: 'Translate from',
      sourceLang: 'Source language',
      to: 'Translate to',
      targetLang: 'Target language',
      languages: ['Uzbek', 'English', 'Russian'],
      notes: 'Additional notes',
      notesPlaceholder: 'Tell us about deadlines, certification requirements, or anything else.',
      submit: 'Get a Quote',
      submitting: 'Sending…',
      submitError: 'Something went wrong. Please try again or email us directly.',
      tooLarge: 'Your files are too large — please keep the total under 20 MB.',
      backHome: '← Back to home',
      successHeading: 'Thanks! Your request has been received',
      successBodyA: 'We’ll review your ',
      successBodyDocOne: 'document',
      successBodyDocMany: 'documents',
      successBodyB: ' and email a quote shortly.',
      backToHome: 'Back to Home',
      submitAnother: 'Submit Another',
    },
  },

  uz: {
    nav: {
      links: [
        { label: 'Bosh sahifa', href: '#home' },
        { label: 'Biz haqimizda', href: '#about' },
        { label: 'Xizmatlar', href: '#services' },
        { label: 'Nima uchun biz?', href: '#why-us' },
        { label: 'Bog‘lanish', href: '#contact' },
      ],
      quote: 'Bepul narx so‘rang',
    },
    hero: {
      eyebrow: 'NAATI sertifikatiga ega tarjimon va og‘zaki tarjima mutaxassisi',
      titleA: 'O‘zbek',
      titleB: 'Ingliz',
      titleTail: 'Tarjima va og‘zaki tarjima xizmatlari',
      body: 'Viza uchun tug‘ilganlik haqidagi guvohnomangizni tarjima qildirmoqchimisiz, muhim uchrashuv uchun tarjimon kerakmi yoki ikki til o‘rtasidagi muloqotda yordam izlayapsizmi? Men sizga boshidan oxirigacha aniq, ishonchli va professional til xizmatlarini taqdim etaman.',
      cta: 'Bepul narx so‘rang',
      phone: '+998 50 576 79 06',
      phoneHref: 'tel:+998505767906',
      imgAlt: 'NAATI sertifikatiga ega o‘zbek–ingliz tarjimoni ish jarayonida',
    },
    about: {
      eyebrow: 'Biz nimalar taklif etamiz',
      heading: 'Keng qamrovli til xizmatlari',
      body: [
        {
          lead: 'NAATI sertifikatiga ega tarjimon.',
          text: ' NAATI (Tarjimon va og‘zaki tarjimonlarni akkreditatsiya qilish bo‘yicha Milliy Agentlik) Avstraliyadagi tarjimonlar va og‘zaki tarjimonlarni sertifikatlovchi milliy tashkilotdir. Avstraliya hukumat idoralari, migratsiya agentlari, universitetlar va boshqa rasmiy muassasalar rasmiy hujjatlar uchun ko‘pincha NAATI sertifikatiga ega tarjimon tomonidan tayyorlangan tarjimalarni talab qiladi yoki tavsiya etadi.',
        },
        {
          text: 'Rasmiy hujjatlar tarjimasidan tortib professional og‘zaki tarjima xizmatlarigacha, jismoniy shaxslar, tadbirkorlar, tadqiqotchilar va turli tashkilotlar uchun ishonchli til xizmatlarini taqdim etaman.',
        },
      ],
    },
    services: {
      eyebrow: 'Xizmatlar',
      heading: 'Tarjima va tarjimonlik xizmatlari',
      body: 'Rasmiy hujjatlar tarjimasidan tortib professional og‘zaki tarjima xizmatlarigacha, o‘zbek va ingliz tillarida ishonchli til xizmatlarini taqdim etaman.',
      cta: 'Narx so‘rash',
      items: [
        {
          title: 'Rasmiy hujjatlar tarjimasi',
          img: '/images/service-certified.png',
          desc: 'Immigratsiya, ta’lim, huquqiy va boshqa rasmiy maqsadlar uchun NAATI sertifikatlangan tarjimalar.',
          bullets: [
            'Tug‘ilganlik haqidagi guvohnoma',
            'Nikoh guvohnomasi',
            'Akademik transkript va diplomlar',
            'Haydovchilik guvohnomasi',
            'Pasport va shaxsni tasdiqlovchi hujjatlar',
          ],
        },
        {
          title: 'Oddiy hujjatlar tarjimasi',
          img: '/images/service-regular.png',
          desc: 'Ingliz, o‘zbek va rus tillariga hamda ushbu tillardan tarjima xizmatlari.',
          bullets: ['Umumiy matnlar', 'Tijorat hujjatlari', 'O‘quv va akademik materiallar'],
        },
        {
          title: 'Og‘zaki tarjima (interpretatsiya)',
          img: '/images/service-interpreting.png',
          desc: 'O‘zbek, ingliz va rus tillari bo‘yicha professional og‘zaki tarjima xizmatlari.',
          bullets: [
            'Telefon orqali',
            'Zoom, Telegram va Skype orqali',
            'Joyiga chiqib xizmat ko‘rsatish (Brisben va Toshkent)',
          ],
        },
        {
          title: 'Tahrirlash va korrektura',
          img: '/images/service-editing.png',
          desc: 'Matningizni ravon, aniq va grammatik jihatdan to‘g‘ri holga keltirish.',
          bullets: ['Kurs ishlari', 'Ilmiy maqolalar', 'Diplom ishlari', 'Uy vazifalari va yozma topshiriqlar'],
        },
      ],
    },
    whyUs: {
      eyebrow: 'Nima uchun bizni tanlaysiz?',
      heading: 'Til bilimlari, tajriba va ishonch bir joyda',
      body: 'Biz o‘zbek, ingliz va rus tillari bo‘yicha professional tarjima va og‘zaki tarjima xizmatlarini taqdim etamiz. Har bir loyiha mazmuni, uslubi va madaniy kontekstini hisobga olgan holda bajariladi. Rasmiy hujjatlar tarjimasidan tortib biznes uchrashuvlari, ilmiy ishlar va kundalik muloqotgacha bo‘lgan barcha ehtiyojlaringiz uchun sifatli va ishonchli xizmat ko‘rsatamiz.',
      points: [
        'NAATI sertifikatiga ega o‘zbek–ingliz tarjimoni va og‘zaki tarjimon (interpreter)',
        'Rasmiy idoralar talablariga mos tarjimalar',
        'Aniq, tabiiy va madaniy jihatdan mos tarjimalar',
        'Tezkor va o‘z vaqtida bajarish',
        'Barcha hujjatlarning maxfiyligi kafolatlanadi',
        'Har bir mijozga individual yondashuv',
      ],
      badge: 'NAATI',
      badgeSub: 'Sertifikatlangan mutaxassis',
      img1Alt: 'Stol ustidagi NAATI sertifikati, guvohnomalar va lug‘at',
      img2Alt: 'O‘zbek va ingliz tilidagi noutbukli tarjimon stoli',
    },
    cta: {
      eyebrow: 'Boshlashga tayyormisiz?',
      heading: 'Bugunoq bepul narx oling',
      body: 'Tarjima yoki og‘zaki tarjima xizmatlari bo‘yicha bepul maslahat va narx olish uchun biz bilan bog‘laning. Sizga mamnuniyat bilan yordam beramiz.',
      cta: 'Bepul narx olish',
      guarantee: 'Avstraliya migratsiya idoralari va muassasalari tomonidan 100% qabul qilinishi kafolatlanadi.',
      guaranteeAlt: 'Avstraliya hukumati Immigratsiya departamenti — 100% qabul kafolati',
    },
    contact: {
      eyebrow: 'Bog‘lanish',
      heading: 'Bepul narx oling',
      body: 'Hujjatlaringizni yuboring yoki savollaringizni yozing. Sizga qisqa vaqt ichida bepul narx taklifi va kerakli ma’lumotlarni taqdim etamiz.',
      cta: 'Bepul narx olish',
      emailLabel: 'Elektron pochta',
      auPhoneLabel: 'Avstraliya',
      uzPhoneLabel: 'O‘zbekiston',
      basedLabel: 'Faoliyat hududi',
      based: 'Brisben, Avstraliya va Toshkent, O‘zbekiston',
    },
    footer: {
      rights: 'Barcha huquqlar himoyalangan.',
    },
    quote: {
      eyebrow: 'Bepul, majburiyatsiz narx',
      heading: 'Bepul narx oling',
      intro: 'Hujjatlaringizni yuklang va nima kerakligini yozing. Biz ularni ko‘rib chiqib, narx taklifini elektron pochtangizga yuboramiz.',
      documents: 'Hujjatlaringiz',
      dropLead: 'Fayllarni bu yerga tashlang yoki ',
      browse: 'tanlang',
      dropHint: 'PDF, Word yoki rasm fayllari — bir nechtasini qo‘shishingiz mumkin',
      removeFile: 'O‘chirish',
      name: 'To‘liq ism',
      namePlaceholder: 'Ism Familiya',
      email: 'Elektron pochta',
      emailPlaceholder: 'siz@example.com',
      phone: 'Telefon',
      phonePlaceholder: '+998 90 000 00 00',
      serviceType: 'Xizmat turi',
      selectService: 'Xizmatni tanlang',
      serviceTypes: [
        'Rasmiy tarjima',
        'Oddiy tarjima',
        'Og‘zaki tarjima',
        'Tahrirlash va korrektura',
      ],
      from: 'Qaysi tildan',
      sourceLang: 'Manba tili',
      to: 'Qaysi tilga',
      targetLang: 'Maqsad tili',
      languages: ['O‘zbek', 'Ingliz', 'Rus'],
      notes: 'Qo‘shimcha izohlar',
      notesPlaceholder: 'Muddatlar, sertifikatlash talablari yoki boshqa tafsilotlarni yozing.',
      submit: 'Narx olish',
      submitting: 'Yuborilmoqda…',
      submitError: 'Xatolik yuz berdi. Iltimos, qayta urinib ko‘ring yoki bizga to‘g‘ridan-to‘g‘ri yozing.',
      tooLarge: 'Fayllaringiz hajmi juda katta — umumiy hajmi 20 MB dan oshmasin.',
      backHome: '← Bosh sahifaga',
      successHeading: 'Rahmat! So‘rovingiz qabul qilindi',
      successBodyA: 'Biz ',
      successBodyDocOne: 'hujjatingizni',
      successBodyDocMany: 'hujjatingizni',
      successBodyB: ' ko‘rib chiqib, tez orada narx taklifini yuboramiz.',
      backToHome: 'Bosh sahifaga qaytish',
      submitAnother: 'Yana yuborish',
    },
  },
};
